version: 1.0
provider:
  name: openfaas
  gateway: https://openfaas-ingress-janaka-steph.cloud.okteto.net
functions:
  react-spa:
    lang: dockerfile
    handler: ./function
    image: registry.cloud.okteto.net/janaka-steph/react-spa